Moved ContextMenu from Xamarin to MAUI
DIPSAS/DIPS.Mobile.UI pull request #23
Opened 2023-04-14 11:32 UTC by Vetle444

* Modified ContextMenu so that it now uses attached property to create a context menu from any element 

* Also added experimental feature: Popover 
iOS: Fully works
Android: Functional, but only with a test popover currently

2023-04-14 12:32 UTC, haavamoa commented
Når jeg testet long pressed effekten merket jeg at på Android på den øverste Frame, så kommer context menyen opp når jeg holder og slipper, mens på den nederste frame kommer context menu opp når jeg holder i et par sekunder. Tenker at siste er riktig, er dette en bug?

2023-04-14 12:36 UTC, Vetle444 commented
@haavamoa Når du holder inne nederste framen skal context-menyen komme når du holder inne, mens øverste skal den komme når du bare trykker

2023-04-14 12:43 UTC, haavamoa requested changes

2023-04-14 12:43 UTC, haavamoa commented on src/app/Components/ComponentsSamples/ContextMenus/ContextMenuSamples.xaml
> +            <dui:ContextMenuEffect.ItemsSource>
Når jeg ser på dette så klarer jeg ikke å forstå at jeg skal begynne en ItemsSource med et ContextMenu. Kanskje propertien ItemsSource her kunne het Menu ettersom det man setter er en ContextMenu?

2023-04-14 12:43 UTC, haavamoa commented on src/app/Components/ComponentsSamples/ContextMenus/ContextMenuSamples.xaml
> +                <dui:ContextMenu VerticalOptions="Start"
Hvorfor må man sette VerticalOptions?

2023-04-14 12:43 UTC, haavamoa commented on src/app/Components/ComponentsSamples/ContextMenus/ContextMenuSamples.xaml
> +                    dui:ContextMenuEffect.HasContextMenu="True">
Vi kunne kanskje ha droppet HasContextMenu property? Det holder muligens å sette ItemsSource for å forstå at man skal ha en context menu?

2023-04-14 12:43 UTC, haavamoa commented on src/library/DIPS.Mobile.UI/Effects/PopoverEffect/iOS/PopoverPlatformEffect.cs
> +public partial class PopoverPlatformEffect
Jeg tenker at dette ikke er en egen effect, og heller ikke en Popover effect. En popover er et vindu som kan ha hva som helst i seg som dukker opp over skjermen. Dette er en effekt som lager en context menu når man bruker "long press". Slik jeg ser det så er dette bare en property på ContextMenuEffect som kan hete `OpenWhen`, som har to properties:
- `Pressed` 
- `LongPressed`

`Pressed` åpner når man trykker på, `LongPressed` åpner når man holder inne.

Usikre på navnet `OpenWhen`, men det er et forslag.

2023-04-14 12:43 UTC, haavamoa commented on src/library/DIPS.Mobile.UI/Effects/ContextMenuEffect/ContextMenuEffect.cs
> +namespace DIPS.Mobile.UI.Effects.ContextMenuEffect;
Gjerne flytt filene og namespace til DIPS.Mobile.UI.ContextMenu, trenger ikke en egen Effects mappe her, liker å holde alt som er relatert til komponenten i en mappe :)

2023-04-14 12:43 UTC, haavamoa commented on src/app/Components/ComponentsSamples/ContextMenus/ContextMenuSamples.xaml
> +        <Frame BackgroundColor="{dui:Colors color_primary_d_90}"
Du kan fjerne denne, den er ikke så interessant. Jeg skjønner at du brukte det for å teste, men den er ikke nødvendig.

2023-04-14 12:43 UTC, haavamoa commented on src/app/Components/ComponentsSamples/ContextMenus/ContextMenuSamples.xaml
> +            <dui:Label Text="Frame with attached popover context menu"
Endre teksten til: Long press context menu

2023-04-17 06:18 UTC, haavamoa requested changes

2023-04-17 06:18 UTC, haavamoa commented on src/library/DIPS.Mobile.UI/AssemblyInfo.cs
> +[assembly: XmlnsDefinition("http://dips.com/mobile.ui", "DIPS.Mobile.UI.Extensions.Markup")]
Er dette noe som henger igjen fra tidligere eller noe som er i bruk?

2023-04-17 06:49 UTC, Vetle444 commented on src/library/DIPS.Mobile.UI/AssemblyInfo.cs
> +[assembly: XmlnsDefinition("http://dips.com/mobile.ui", "DIPS.Mobile.UI.Extensions.Markup")]
Va eg som hadde brukt, men som eg ikje treng allikavell 😄

2023-04-17 06:56 UTC, haavamoa approved these changes

2023-04-17 06:56 UTC, merged