Added HeaderPositioning to dui:CollectionView
DIPSAS/DIPS.Mobile.UI pull request #381
Opened 2024-03-20 09:30 UTC by GovermanGambo

### Description of Change
- Added HeaderPositioning to dui:CollectionView
  - Normal: Header scrolls along with the collection view content
  - Sticky: Header sticks to the top of the collection view, over the content
  - PartialSticky: Header scrolls along with the collection view content, but will reappear and stick while scrolling upwards

### Todos
- [x] I have tested on an Android device.
- [x] I have tested on an iOS device.
- [ ] I have supported accessibility

2024-03-20 09:31 UTC, GovermanGambo commented
Tester litt oppførsel i Arena Mobil

2024-03-20 09:31 UTC, GovermanGambo commented on src/library/DIPS.Mobile.UI/Components/Lists/CollectionView/CollectionView.Properties.cs
> +public enum CollectionViewHeaderPositioning
Forslag til bedre navngivinger?

2024-03-20 09:36 UTC, haavamoa requested changes

2024-03-20 09:36 UTC, haavamoa commented on src/library/DIPS.Mobile.UI/Components/Lists/CollectionView/CollectionView.Properties.cs
> +public enum CollectionViewHeaderPositioning
Ettersom dette ligger i namespace CollectionView trenger du ikke prefix CollectionView i hvert fall. 

HeaderPositioning høres greit ut det :)

2024-03-24 13:12 UTC, haavamoa approved these changes

2024-04-08 12:31 UTC, haavamoa commented
@GovermanGambo skal denne inn?

2024-06-13 12:34 UTC, Vetle444 commented
Skal denne inn?

2024-07-01 14:55 UTC, Vetle444 commented
Looking forward to this feature

2024-07-29 08:22 UTC, Vetle444 commented
Can't wait!

2024-08-09 11:17 UTC, Vetle444 commented
This will be groundbreaking!

2024-10-01 07:29 UTC, Vetle444 commented
This should be showcased in the next .NET conf!

2024-10-11 11:07 UTC, Vetle444 commented
Nu har du testa oppførsel i et halvt år

2024-11-15 13:36 UTC, Vetle444 commented
Såg ikje denna i .NET 9 confen ??

2024-11-15 14:30 UTC, closed without merging